# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.URLField()),
                ('commands_queue', models.CharField(max_length=100)),
            ],
        ),
    ]
