# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survcam', '0002_auto_20160315_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='resolution',
            field=models.CharField(choices=[('640x480', '640x480'), ('1296x730', '1296x730'), ('1296x972', '1296x972'), ('1024x768', '1024x768'), ('2592x1944', '2592x1944'), ('1920x1080', '1920x1080')], default='1024x768', max_length=100),
        ),
    ]
