# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survcam', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='commands_queue',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='fps',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
    ]
